config/routes.rb
Workarea::Admin::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resources :users, only: [] do
      get :wish_list
    end

    resource :report, only: [] do
      get :wish_list_products
    end
  end
end

Workarea::Storefront::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resources :wish_lists, only: [:index, :show]

    namespace :users do
      resource :wish_list, only: :show do
        post 'from_cart_item/:item_id', as: :from_cart, action: 'create_from_cart_item'
        post 'add_item', as: :add_to
        patch 'update_item_quantity/:item_id', as: :update_item, action: 'update_item_quantity'
        patch 'update', as: :update
        delete 'remove_item', as: :remove_from
      end
    end

    post 'analytics/wish_list_add/:product_id', to: 'analytics#wish_list_add', as: :analytics_wish_list_add
    post 'analytics/wish_list_remove/:product_id', to: 'analytics#wish_list_remove', as: :analytics_wish_list_remove
  end
end

app/views/workarea/admin/dashboards/_wish_list_products_card.html.haml
.grid__cell
  .card{ class: card_classes(:wish_list_products_report, local_assigns[:active]) }
    = link_to wish_list_products_report_path, class: 'card__header' do
      %span.card__header-text= t('workarea.admin.reports.wish_list_products.title')
      = inline_svg 'workarea/admin/icons/insights.svg', class: 'card__icon'

    .card__body
      .card__centered-content
        %table
          %tbody
            - dashboard.wish_list_products.results.take(4).each do |result|
              %tr
                %td= result.product.present? ? result.product.name : result._id
                %td.align-right= number_to_currency(result.revenue)

        = link_to wish_list_products_report_path, class: 'card__button' do
          %span.button.button--small= t('workarea.admin.dashboards.reports.view_full_report')