config/routes.rb
Workarea::Admin::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resources :users, only: [] do
      get :wish_list
    end

    resource :report, only: [] do
      get :wish_list_products
    end
  end
end

Workarea::Storefront::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resources :wish_lists, only: [:index, :show]

    namespace :users do
      resource :wish_list, only: :show do
        post 'from_cart_item/:item_id', as: :from_cart, action: 'create_from_cart_item'
        post 'add_item', as: :add_to
        patch 'update_item_quantity/:item_id', as: :update_item, action: 'update_item_quantity'
        patch 'update', as: :update
        delete 'remove_item', as: :remove_from
      end
    end

    post 'analytics/wish_list_add/:product_id', to: 'analytics#wish_list_add', as: :analytics_wish_list_add
    post 'analytics/wish_list_remove/:product_id', to: 'analytics#wish_list_remove', as: :analytics_wish_list_remove
  end
end

app/models/workarea/wish_list.rb
module Workarea
  class WishList
    include ApplicationDocument
    include UrlToken

    class InvalidToken < StandardError; end

    field :user_id, type: String
    field :email, type: String
    field :first_name, type: String
    field :last_name, type: String
    field :name, type: String
    field :location, type: String
    field :privacy, type: String, default: 'public'

    index({ user_id: 1 }, { unique: true })
    index(first_name: 1)
    index(last_name: 1)
    index(name: 1)
    index(email: 1)

    index(token: 1, privacy: 1)

    embeds_many :items, class_name: 'Workarea::WishList::Item'

    validates :privacy,
              presence: true,
              inclusion: { in: %w(public shared private) }

    scope :named, -> { where(:name.exists => true, :name.ne => '') }

    before_create :set_user_details

    # Gets a wish list for a user.
    #
    # @param [String] user_id
    #
    # @return [WishList]
    #
    def self.for_user(user_id)
      existing = Workarea::WishList.where(user_id: user_id).first
      existing || Workarea::WishList.create!(user_id: user_id)
    end

    # Find wish lists for public viewing.
    # Only returns wish lists with public privacy setting.
    #
    # @param [String] query
    #   name or email
    # @param [String] location
    #   city, state, postal code
    #
    # @return [Array]
    #
    def self.search(query, location = '')
      Workarea::WishList::PublicSearch.new(
        query,
        location
      ).results
    end

    # Find a wish list by the share token
    #
    # @param [String] token
    #
    # @return [WishList]
    #
    def self.find_by_token(token)
      raise(InvalidToken, token) if token.blank?

      Workarea::WishList.where(
        token: token,
        :privacy.ne => 'private'
      ).first || raise(InvalidToken, token)
    end

    # Find a list of product ids in a user's wish list
    #
    # @param [String, BSON::ObjectId] user_id
    #
    # @return [Array]
    #
    def self.find_products(user_id)
      wish_list = Workarea::WishList.where(user_id: user_id).first
      wish_list ? wish_list.items.map(&:product_id) : []
    end

    %w(public shared private).each do |privacy_level|
      define_method "#{privacy_level}?" do
        privacy == privacy_level
      end
    end

    # How many valid units are in the wish list
    #
    # @return [Integer]
    #
    def quantity
      items.select(&:valid?).sum(&:quantity)
    end

    # Get unpurchased items
    #
    # @return [Array]
    #
    def unpurchased_items
      items.reject(&:purchased?)
    end

    # Get items from this list that have been purchased
    #
    # @return [Array]
    #
    def purchased_items
      items.select(&:purchased?)
    end

    # Add a wish list item
    #
    # @param [String] product_id
    # @param [String] sku
    # @param [Integer] quantity
    #
    # @return [Boolean]
    #   whether the item was saved
    #
    def add_item(product_id, sku, quantity = 1, details = {}, customizations = {})
      if existing_item = items.where(sku: sku, customizations: customizations).first
        change_quantity(sku, existing_item.quantity + quantity)
      else
        items.build(
          product_id:     product_id,
          sku:            sku,
          quantity:       quantity,
          details:        details,
          customizations: customizations
        )
      end

      save
    end

    # Update a wish list item's quantity
    #
    # @param [String] item_id
    # @param [Integer] quantity
    #
    # @return [Boolean]
    #   whether the item was saved
    #

    def update_item_quantity(item_id, quantity)
      item = items.where(id: item_id).first
      return false if item.nil?
      item.update_attributes(quantity: quantity)
    end

    # Mark the items as being purchased
    #
    # @param [Array] skus
    #
    # @return [self]
    #
    def mark_item_purchased(sku, quantity)
      item = items.detect { |i| i.sku == sku }
      if item
        item.received = item.received + quantity
        item.purchased = true
      end
      save!
    end

    # Remove a SKU from the wish list
    #
    # @param [String] sku
    #
    # @return [self]
    #
    def remove_item(sku)
      items.where(sku: sku).first.delete
      save
    end

    def price_adjustments
      PriceAdjustmentSet.new(
        (items.map(&:price_adjustments).flatten || [])
      )
    end

    def reset_pricing!
      items.each(&:reset_pricing!)
      self
    end

    def segment_ids
      []
    end

    private

    def change_quantity(sku, quantity)
      item = items.where(sku: sku).first
      item.quantity = quantity
    end

    def set_user_details
      return unless user_id.present?
      SetWishListDetails.new(self).perform
    end
  end
end

app/models/workarea/wish_list/item.rb
module Workarea
  class WishList::Item
    include ApplicationDocument

    field :product_id, type: String
    field :quantity, type: Integer, default: 1
    field :received, type: Integer, default: 0
    field :sku, type: String
    field :product_details, type: Hash, default: {}
    field :sku_details, type: Hash, default: {}
    field :customizations, type: Hash, default: {}
    field :purchased, type: Boolean, default: false
    field :discountable, type: Boolean, default: true
    field :contributes_to_shipping, type: Boolean, default: true
    field :product_attributes, type: Hash, default: {}
    field :total_price, type: Money, default: 0

    embedded_in :wish_list, inverse_of: :items

    embeds_many :price_adjustments,
                class_name: 'Workarea::PriceAdjustment',
                extend: Workarea::PriceAdjustmentExtension

    validates :product_id, presence: true
    validates :sku, presence: true
    validates :quantity, presence: true,
                         numericality: {
                           greater_than_or_equal_to: 1,
                           only_integer: true
                         }

    def details=(details)
      write_attributes(
        details.slice(
          :product_details,
          :sku_details,
          :product_attributes
        )
      )

      self
    end

    # Adds a price adjustment to the item. Does not persist.
    #
    # @return [self]
    #
    def adjust_pricing(options = {})
      price_adjustments.build(options)
    end

    # Clears out all pricing for this item.
    #
    def reset_pricing!
      price_adjustments.delete_all
    end

    # The base price per-unit for this item.
    #
    # @return [Money]
    #
    def unit_price
      price_adjustments.first.unit.to_m
    end

    # Whether this item is on sale (as of the last time the
    # order was priced).
    #
    # @return [Boolean]
    #
    def on_sale?
      !!price_adjustments.first.data['on_sale']
    end
  end
end

app/models/workarea/wish_list/pricing.rb
module Workarea
  module WishList::Pricing
    # Build price adjustments and set order total prices.
    #
    # @param [Workarea::WishList] wish_list
    # @return [self]
    #
    def self.perform(wish_list)
      wish_list.reset_pricing!
      WishList::Request.new(wish_list).run
      self
    end
  end
end

app/models/workarea/wish_list/pricing/calculators/totals_calculator.rb
module Workarea
  class WishList::Pricing::Calculators::TotalsCalculator
    attr_reader :wish_list, :request

    def initialize(wish_list, request = nil)
      @wish_list = wish_list
      @request = request
    end

    def adjust
      set_item_totals
    end

    private

    def price_adjustments
      @price_adjustments ||= @wish_list.price_adjustments # Memoize for perf
    end

    def set_item_totals
      @wish_list.items.each do |item|
        item.total_price = item.price_adjustments.adjusting('item').sum
      end
    end
  end
end

app/models/workarea/wish_list/public_search.rb
module Workarea
  class WishList::PublicSearch
    attr_reader :query, :location

    def initialize(query, location = '')
      @query    = query
      @location = location
    end

    def results
      regex = /^#{Regexp.quote(query)}/i
      criteria = [
        { name: regex },
        { first_name: regex },
        { last_name: regex },
        { email: query } # we don't want partial matching on email
      ]

      if location.present?
        loc_regex = /.*#{Regexp.quote(location)}.*/i
        Workarea::WishList.where(
          privacy: 'public',
          location: loc_regex,
          '$or' => criteria
        )
      else
        Workarea::WishList.where(
          privacy: 'public',
          '$or' => criteria
        )
      end.named
    end
  end
end

app/models/workarea/wish_list/request.rb
module Workarea
  module Pricing
    class WishList::Request
      delegate :items, to: :order

      def initialize(wish_list)
        @wish_list = wish_list
      end

      def pricing
        @pricing ||= Pricing::Collection.new(all_skus)
      end

      def order
        @wish_list
      end

      def run
        Workarea.config.wish_list_pricing_calculators.each do |klass|
          klass.constantize.new(self).adjust
        end
      end

      private

      def all_skus
        skus = [
          @wish_list.items.map(&:sku),
          @wish_list.items.map { |i| i.customizations['pricing_sku'] }
        ]

        skus.flatten.reject(&:blank?).uniq
      end
    end
  end
end

app/controllers/workarea/storefront/users/wish_lists_controller.rb
module Workarea
  module Storefront
    class Users::WishListsController < Storefront::ApplicationController
      skip_before_action :verify_authenticity_token, only: [:add_item]
      before_action :store_item_in_session, only: :add_item, unless: :logged_in?
      before_action :store_item_in_session_when_moving_to_cart, only: :create_from_cart_item, unless: :logged_in?
      before_action :require_login_and_redirect
      before_action :add_item_from_session, only: :show, if: :item_stored_in_session?
      before_action :validate_customizations, only: :add_item

      def show
        WishList::Pricing.perform(current_wish_list)
        @wish_list = WishListViewModel.new(
          current_wish_list,
          view_model_options
        )
      end

      def update
        current_wish_list.update_attributes(params.permit(:privacy))
        flash[:success] =
          t('workarea.storefront.flash_messages.wish_list_updated')
        redirect_to users_wish_list_path
      end

      def update_item_quantity
        if current_wish_list.update_item_quantity(params[:item_id], params[:quantity].to_i)
          flash[:success] =
            t('workarea.storefront.flash_messages.wish_list_item_updated')
        end
        redirect_to users_wish_list_path
      end

      def create_from_cart_item
        item = current_order.items.find(params[:item_id])
        current_wish_list.add_item(
          item.product_id,
          item.sku,
          item.quantity,
          OrderItemDetails.find!(item.sku).to_h,
          item.customizations
        )
        current_order.remove_item(params[:item_id])

        flash[:success] =
          t('workarea.storefront.flash_messages.item_moved_to_wish_list')
        redirect_to users_wish_list_path
      end

      def add_item
        current_wish_list.add_item(
          product_id,
          sku,
          params[:quantity].to_i,
          OrderItemDetails.find!(sku).to_h,
          customizations.try(:to_h) || {}
        )
        flash[:success] =
          t('workarea.storefront.flash_messages.wish_list_item_added')
        redirect_to users_wish_list_path
      end

      def remove_item
        current_wish_list.remove_item(params[:sku])
        flash[:success] =
          t('workarea.storefront.flash_messages.wish_list_item_removed')
        redirect_to users_wish_list_path
      end

      private

      def require_login_and_redirect
        result = require_login
        remember_location(users_wish_list_path) if result == false
        result
      end

      def current_wish_list
        @wish_list ||= WishList.for_user(current_user.id)
      end

      def store_item_in_session
        wish_list_session.store_item(params.merge(customizations: customizations.try(:to_h) || {}))
      end

      def store_item_in_session_when_moving_to_cart
        item = current_order.items.where(id: params[:item_id]).first
        wish_list_session.store_item(item.attributes.merge(item_id: params[:item_id]))
      end

      def add_item_from_session
        item_id = cookies[:wish_list_item_id]

        wish_list_session.add_item(current_wish_list)
        current_order.remove_item(item_id) if current_order.items.where(id: item_id).present?
      end

      def wish_list_session
        WishListSession.new(cookies)
      end

      def item_stored_in_session?
        cookies.key?(:wish_list_product_id)
      end

      def customizations
        @customizations ||= Catalog::Customizations.find(product_id, params.to_unsafe_h)
      end

      def validate_customizations
        if customizations.present? && !customizations.valid?
          flash[:error] = customizations.errors.full_messages.join(', ')
          product = Catalog::Product.find(product_id)

          redirect_back(fallback_location: product_path(product))
          return false
        end
      end

      def product_id
        params[:product_id]
      end

      def sku
        params[:sku]
      end
    end
  end
end

app/controllers/workarea/storefront/wish_lists_controller.rb
module Workarea
  module Storefront
    class WishListsController < Storefront::ApplicationController
      def index
        if params[:wish_list_query].present?
          @wish_lists = WishList
                        .search(params[:wish_list_query], params[:location])
                        .page(params[:page] || 1)
        end
      end

      def show
        wish_list = WishList.find_by_token(params[:id])
        WishList::Pricing.perform(wish_list)
        @wish_list = WishListViewModel.new(
          wish_list,
          view_model_options
        )
      end
    end
  end
end

app/helpers/workarea/storefront/wish_list_analytics_helper.rb
module Workarea
  module Storefront
    module WishListAnalyticsHelper
      def add_to_wish_list_analytics_data(product)
        {
          event: 'addToWishList',
          domEvent: 'click',
          payload: product_analytics_data(product)
        }
      end

      def remove_from_wish_list_analytics_data(product)
        {
          event: 'removeFromWishList',
          domEvent: 'submit',
          payload: product_analytics_data(product)
        }
      end
    end
  end
end

app/views/workarea/storefront/wish_lists/_wish_lists_link.html.haml
.grid__cell
  .wish-lists__link
    = link_to users_wish_list_path do
      %span= t('layouts.workarea.storefront.wish_lists_link.your_wish_list')

app/views/workarea/storefront/wish_lists/index.html.haml
- @title = t('workarea.storefront.wish_lists.find_title')

.view

  %h1= t('workarea.storefront.wish_lists.find_title')
  %p= t('workarea.storefront.wish_lists.find_instructions')

  - if params[:wish_list_query]
    %h2= t('workarea.storefront.wish_lists.results')

    - unless @wish_lists.present?
      %p= t('workarea.storefront.searches.no_results', terms: params[:wish_list_query])

    - else
      %ol
        - @wish_lists.each do |wish_list|
          %li= link_to wish_list.name, wish_list_path(wish_list.token)

    %h2= t('workarea.storefront.searches.search_again')

  = form_tag wish_lists_path, method: 'get', id: 'find_wish_list_form' do
    .property
      = label_tag 'name_or_email', nil, class: 'property__name' do
        %span.property__text= t('workarea.storefront.wish_lists.name_or_email')
      .value= text_field_tag :wish_list_query, params[:wish_list_query], id: 'name_or_email', class: 'text-box', required: true
    .property
      = label_tag :location, nil, class: 'property__name' do
        %span.property__text= t('workarea.storefront.wish_lists.location')
        %span.property__requirement.property__requirement--optional= t('workarea.storefront.forms.optional')
      .value= text_field_tag :location, params[:location], class: 'text-box'

    %p= button_tag t('workarea.storefront.searches.search'), value: 'search', class: 'button'

app/views/workarea/storefront/wish_lists/show.html.haml
- @title = t('workarea.storefront.wish_lists.show_title', name: @wish_list.name)

= render_schema_org(breadcrumb_list_schema([[t('workarea.storefront.layouts.home'), root_path], [t('workarea.storefront.wish_lists.find_title'), wish_lists_path], [@wish_list.name, wish_list_path(@wish_list)]]))

- content_for :breadcrumbs do
  %p.breadcrumbs__node-group
    %span.breadcrumbs__node
      = link_to t('workarea.storefront.layouts.home'), root_path, rel: 'home'
    %span.breadcrumbs__node
      = link_to t('workarea.storefront.wish_lists.find_title'), wish_lists_path
    %span.breadcrumbs__node= t('workarea.storefront.wish_lists.show_title', name: @wish_list.name)

.wish-lists.view

  %h1= t('workarea.storefront.wish_lists.show_title', name: @wish_list.name)

  .wish-lists__section

    .browsing-controls
      = form_tag wish_list_path(params[:id]), method: :get, class: 'browsing-controls__form' do
        %p.browsing-controls__form-item.property
          = label_tag :state, nil, class: 'property__name' do
            %span.property__text= t('workarea.storefront.wish_lists.show')
          %span.value= select_tag :state, options_for_select(@wish_list.state_options, params[:state]), data: { form_submitting_control: '' }
        %p.browsing-controls__form-item.hidden-if-js-enabled= button_tag t('workarea.storefront.forms.go'), class: 'button'

    - if @wish_list.items.empty?

      %p= @wish_list.empty_text

    - else

      %ul.product-list
        - @wish_list.items.each do |item|
          = render_schema_org(product_schema(item.product))

          %li.product-list__item
            .product-list__item-cell
              .product-list__summary
                %p.product-list__media= link_to image_tag(product_image_url(item.primary_image, :small_thumb), alt: item.name, class: 'product-list__media-image'), product_url(item.product, sku: item.sku), class: 'product-list__media-link'
                .product-list__info
                  %p.product-list__name= link_to item.name, product_path(item.product, sku: item.sku)
                  %p.product-list__id= item.sku_name
                  %p= item.inventory_status
                  - if item.has_options?
                    .product-list__option-group
                      - item.details.each do |name, value|
                        %p.product-list__option #{name.titleize}: #{value}
                      - item.customizations.each do |name, value|
                        %p.product-list__option #{name.titleize}: #{value}
            = form_tag cart_items_path, class: 'product-list__item-cell', data: { dialog_form: { dialogOptions: { closeAll: true, initModules: true } }, analytics: add_to_cart_analytics_data(item.product).to_json } do
              = hidden_field_tag :product_id, item.product_id, id: nil
              = hidden_field_tag :sku, item.sku, id: nil
              = hidden_field_tag :via, @wish_list.to_gid_param, id: nil
              - item.customizations.each do |param, value|
                = hidden_field_tag param, value, id: nil
              %table.table
                %thead
                  %tr
                    %th.table__prices= t('workarea.storefront.orders.price')
                    %th.table__quantity= t('workarea.storefront.wish_lists.requested')
                    %th.table__quantity= t('workarea.storefront.wish_lists.received')
                    %th.table__quantity= t('workarea.storefront.orders.quantity')
                    %th.table__prices= t('workarea.storefront.orders.total')
                %tbody
                  %tr
                    %td.table__prices
                      - if item.on_sale?
                        %p.table__price
                          %span.table__price-label= t('workarea.storefront.orders.price_now')
                          %strong.table__price-discount.wish-lists__public-item-price= number_to_currency(item.unit_price, exchange: false)
                        %p.table__price
                          %span.table__price-label= t('workarea.storefront.orders.price_was')
                          %s= number_to_currency(item.original_price, exchange: false)
                      - else
                        %p.table__price
                          %span.wish-lists__public-item-price= number_to_currency(item.unit_price, exchange: false)
                      - if item.customized?
                        %p.table__price
                          %span.table__price-label= t('workarea.storefront.orders.customizations')
                          %span= number_to_currency item.customizations_unit_price
                    %td.table__quantity= item.quantity
                    %td.table__quantity= item.received
                    %td.table__quantity
                      .value= number_field_tag :quantity, item.quantity, class: 'text-box text-box--x-small wish-lists__public-quantity-field', min: 1, id: nil
                    %td.table__prices
                      - if item.total_adjustments.many?
                        %p.table__price
                          %span.table__price-label= t('workarea.storefront.orders.subtotal')
                          %span= number_to_currency item.prediscount_price
                        - item.total_adjustments.each do |adjustment|
                          %p.table__price
                          %span= adjustment.description.titleize
                          %span= number_to_currency(adjustment.amount)
                      %p.table__price
                        %span.wish-lists__public-total-price= number_to_currency(item.total_price, exchange: false)
              .grid.grid--auto.grid--middle
                .grid__cell
                  - if item.purchasable?
                    %p= button_tag t('workarea.storefront.products.add_to_cart'), class: 'button'
                  - else
                    %p.unavailable= t('workarea.storefront.products.unavailable')