config/routes.rb
Workarea::Admin::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resources :users, only: [] do
      get :wish_list
    end

    resource :report, only: [] do
      get :wish_list_products
    end
  end
end

Workarea::Storefront::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resources :wish_lists, only: [:index, :show]

    namespace :users do
      resource :wish_list, only: :show do
        post 'from_cart_item/:item_id', as: :from_cart, action: 'create_from_cart_item'
        post 'add_item', as: :add_to
        patch 'update_item_quantity/:item_id', as: :update_item, action: 'update_item_quantity'
        patch 'update', as: :update
        delete 'remove_item', as: :remove_from
      end
    end

    post 'analytics/wish_list_add/:product_id', to: 'analytics#wish_list_add', as: :analytics_wish_list_add
    post 'analytics/wish_list_remove/:product_id', to: 'analytics#wish_list_remove', as: :analytics_wish_list_remove
  end
end

app/controllers/workarea/storefront/users/wish_lists_controller.rb
module Workarea
  module Storefront
    class Users::WishListsController < Storefront::ApplicationController
      skip_before_action :verify_authenticity_token, only: [:add_item]
      before_action :store_item_in_session, only: :add_item, unless: :logged_in?
      before_action :store_item_in_session_when_moving_to_cart, only: :create_from_cart_item, unless: :logged_in?
      before_action :require_login_and_redirect
      before_action :add_item_from_session, only: :show, if: :item_stored_in_session?
      before_action :validate_customizations, only: :add_item

      def show
        WishList::Pricing.perform(current_wish_list)
        @wish_list = WishListViewModel.new(
          current_wish_list,
          view_model_options
        )
      end

      def update
        current_wish_list.update_attributes(params.permit(:privacy))
        flash[:success] =
          t('workarea.storefront.flash_messages.wish_list_updated')
        redirect_to users_wish_list_path
      end

      def update_item_quantity
        if current_wish_list.update_item_quantity(params[:item_id], params[:quantity].to_i)
          flash[:success] =
            t('workarea.storefront.flash_messages.wish_list_item_updated')
        end
        redirect_to users_wish_list_path
      end

      def create_from_cart_item
        item = current_order.items.find(params[:item_id])
        current_wish_list.add_item(
          item.product_id,
          item.sku,
          item.quantity,
          OrderItemDetails.find!(item.sku).to_h,
          item.customizations
        )
        current_order.remove_item(params[:item_id])

        flash[:success] =
          t('workarea.storefront.flash_messages.item_moved_to_wish_list')
        redirect_to users_wish_list_path
      end

      def add_item
        current_wish_list.add_item(
          product_id,
          sku,
          params[:quantity].to_i,
          OrderItemDetails.find!(sku).to_h,
          customizations.try(:to_h) || {}
        )
        flash[:success] =
          t('workarea.storefront.flash_messages.wish_list_item_added')
        redirect_to users_wish_list_path
      end

      def remove_item
        current_wish_list.remove_item(params[:sku])
        flash[:success] =
          t('workarea.storefront.flash_messages.wish_list_item_removed')
        redirect_to users_wish_list_path
      end

      private

      def require_login_and_redirect
        result = require_login
        remember_location(users_wish_list_path) if result == false
        result
      end

      def current_wish_list
        @wish_list ||= WishList.for_user(current_user.id)
      end

      def store_item_in_session
        wish_list_session.store_item(params.merge(customizations: customizations.try(:to_h) || {}))
      end

      def store_item_in_session_when_moving_to_cart
        item = current_order.items.where(id: params[:item_id]).first
        wish_list_session.store_item(item.attributes.merge(item_id: params[:item_id]))
      end

      def add_item_from_session
        item_id = cookies[:wish_list_item_id]

        wish_list_session.add_item(current_wish_list)
        current_order.remove_item(item_id) if current_order.items.where(id: item_id).present?
      end

      def wish_list_session
        WishListSession.new(cookies)
      end

      def item_stored_in_session?
        cookies.key?(:wish_list_product_id)
      end

      def customizations
        @customizations ||= Catalog::Customizations.find(product_id, params.to_unsafe_h)
      end

      def validate_customizations
        if customizations.present? && !customizations.valid?
          flash[:error] = customizations.errors.full_messages.join(', ')
          product = Catalog::Product.find(product_id)

          redirect_back(fallback_location: product_path(product))
          return false
        end
      end

      def product_id
        params[:product_id]
      end

      def sku
        params[:sku]
      end
    end
  end
end

app/views/workarea/admin/users/_wish_list_card.html.haml
.grid__cell
  .card{ class: card_classes(:wish_list, local_assigns[:active]) }
    = link_to user_wish_list_path(model), class: 'card__header' do
      %span.card__header-text= t('workarea.admin.users.cards.wish_list.title')
      = inline_svg 'workarea/admin/icons/featured_products.svg', class: 'card__icon'

    - if local_assigns[:active].blank?
      .card__body
        - if model.wish_list.items.empty?
          .card__empty-note
            %p= t('workarea.admin.users.cards.wish_list.empty')
          = link_to user_wish_list_path(model), class: 'card__button' do
            %span.button.button--small= t('workarea.admin.users.cards.wish_list.button')
        - else
          %ol.grid
            - model.wish_list.items.take(4).each_with_index do |item, i|
              %li.grid__cell.grid__cell--50
                .card__photo-box
                  - if i == 3 && model.wish_list.items.size > 4
                    %span.card__photo +#{model.wish_list.items.size - i}
                  - else
                    = image_tag product_image_url(item.product.primary_image, :medium), alt: item.product.name, class: 'card__photo'
          = link_to user_wish_list_path(model), class: 'card__button' do
            %span.button.button--small= t('workarea.admin.users.cards.wish_list.button')

app/views/workarea/admin/users/_wish_list_item_summary.html.haml
.summary
  = link_to catalog_product_path(model.product) do
    .summary__image-container
      = image_tag(product_image_url(model.product.primary_image, :medium), alt: model.name, class: 'summary__image') if model.product.primary_image.present?
    %span.summary__name= model.name
    .summary__info-container
      %span.summary__info #{t('workarea.admin.users.wish_list.quantity')}: #{model.quantity}
      %span.summary__info= model.sku_name

app/views/workarea/admin/users/_wishlist_import_export_nav.html.haml
.grid.grid--auto.grid--right.grid--middle
  .grid__cell= link_to t('workarea.admin.users.wish_list_import_export_nav.wish_lists'), '#export-wish-lists', data: { tooltip: { interactive: true, side: 'bottom' } }

#export-wish-lists.tooltip-content
  %p= t('workarea.admin.users.wish_list_import_export_nav.description')
  .align-center
    = link_to t('workarea.admin.users.wish_list_import_export_nav.import'), new_data_file_import_path(model_type: Workarea::WishList), return_to: users_path, class: 'text text--bold'
    %span= t('workarea.admin.users.wish_list_import_export_nav.or')
    = link_to t('workarea.admin.users.wish_list_import_export_nav.export'), new_data_file_export_path(model_type: Workarea::WishList), return_to: users_path, class: 'text text--bold'

app/views/workarea/admin/users/wish_list.html.haml
- @page_title = t('workarea.admin.users.wish_list.title', user: @user.name)

.view
  .view__header
    .grid.grid--middle.grid--center
      .grid__cell.grid__cell--50
        .view__heading
          = link_to_index_for(@user)
          %h1= t('workarea.admin.users.wish_list.title_html', user: link_to(@user.name, url_for(@user)))

  .view__container
    = render_cards_for(@user, :wish_list)

  .view__container
    .browsing-controls.browsing-controls--with-divider.browsing-controls--center.browsing-controls--filters-displayed
      = form_tag user_wish_list_path(@user), method: 'get', id: 'user_wish_list_form' do
        .browsing-controls__filter
          .property.property--inline
            = label_tag 'state', t('workarea.admin.users.wish_list.state'), class: 'property__name'
            = select_tag :state, options_for_select(@user.wish_list.state_options, params[:state]), data: { form_submitting_control: '' }

    %p.align-center= pluralize(@user.wish_list.items.count, t('workarea.admin.users.wish_list.item'))

    .grid.grid--auto.grid--flush.grid--center
      - @user.wish_list.items.each do |item|
        .grid__cell= render 'workarea/admin/users/wish_list_item_summary', model: item